### PR TITLE
Upgrade to 6.8.4 and 7.4.2

### PR DESCRIPTION
**Pull request by dpursehouse**

### CODE REVIEW

**Comment by blacktop** [comment]
Hi! 

Can you please also update the Dockerfile in the x-pack folder?

Did you run `make update` to generate your sha512s?  Did you run `make all` ?

Thanks!

**Comment by dpursehouse** [comment]
> Can you please also update the Dockerfile in the x-pack folder?
> 
Done in 0f4b56b6350c54a8a65b3e5033fa8795ac312689

> Did you run `make update` to generate your sha512s?
> 
I took the sha512s from the files on the download site.  [For 6.8.4](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.4.tar.gz.sha512) and [for 7.4.2](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.4.2-no-jdk-linux-x86_64.tar.gz.sha512)

> Did you run `make all` ?
> 

Not yet, otherwise I would have noticed the wrong sha512 that I just fixed in 40f70b1681be2690b1149bdb9257503a35396282 :/

**Comment by blacktop** [comment]
Right on! 

Yeah in the future you can just run `make update` to pull the sha512's from the elasitc.co website.

LGTM, Thank you!!

**Comment by dpursehouse** [comment]
> Yeah in the future you can just run `make update` to pull the sha512's from the elasitc.co website.

Thanks.  Good to know.

I was just running `make test` and it's failing with:

```
make: wait-for-es: No such file or directory
```

 I see references to that were removed to fix CI in c1dab348b8def4a0c9b4bce02e73db627fb93b48 but it seems the Makefile is still referring to it.

**Comment by blacktop** [comment]
yeah its a golang binary I wrote: https://github.com/blacktop/wait-for-es

It works better than other things I have used in the past, but mostly it is useful for blocking make/ci servers while elasticsearch spins up.

**Comment by dpursehouse** [comment]
OK, then should the Makefile be updated to fetch it, or should that be added to the repo?

**Pull request merged**
