### PR TITLE
Update versions 6 and 7

### PR DESCRIPTION
**Pull request by marco-miller**
`make all` => `"testcluster"` in green locally.

### CODE REVIEW

**Comment by blacktop** [comment]
Looks good to me! @marco-miller Would you mind if I added you as a maintainer on this repo?

**Comment by marco-miller** [comment]
> Looks good to me! @marco-miller Would you mind if I added you as a maintainer on this repo?

I'd be interested, yes; thanks. What would be the expectations, or items to cover for the role? And, I suppose that this role would remain shared along with you or a few co-owners(?)

**Comment by marco-miller** [comment]
> > Looks good to me! @marco-miller Would you mind if I added you as a maintainer on this repo?
> 
> I'd be interested, yes; thanks. What would be the expectations, or items to cover for the role? And, I suppose that this role would remain shared along with you or a few co-owners(?)

Not sure if you noticed my follow-up question above. Anyway, if the role is trivially becoming co-owner, please add me, sure. -Thanks! :)

**Comment by marco-miller** [comment]
> > > Looks good to me! @marco-miller Would you mind if I added you as a maintainer on this repo?
> > 
> > 
> > I'd be interested, yes; thanks. What would be the expectations, or items to cover for the role? And, I suppose that this role would remain shared along with you or a few co-owners(?)
> 
> Not sure if you noticed my follow-up question above. Anyway, if the role is trivially becoming co-owner, please add me, sure. -Thanks! :) @blacktop

@blacktop -if still willing to add me as maintainer for this repo, I might need access to publish on docker hub; WDYT?

**Comment by blacktop** [comment]
@marco-miller my apologies for being so slow to respond, work has been **insane** these past few weeks. 😩  I have invited you to be a collaborator on this repo.  I am also open to adding you as a collaborator to the dockerhub repo.  What is your dockerhub account name?

**Comment by marco-miller** [comment]
Sure, no problem. Work happens ;) -My id is marcomiller.

**Comment by marco-miller** [comment]
> @marco-miller my apologies for being so slow to respond, work has been **insane** these past few weeks. 😩 I have invited you to be a collaborator on this repo. I am also open to adding you as a collaborator to the dockerhub repo. What is your dockerhub account name?

Not sure if you noticed my previous answer, @blacktop; my dh name is `marcomiller`. I just pushed commit 8e71e24 and its parent commit d7b5a48. Will their new images be pushed automatically and successfully to dh, or should I eventually try `make push` locally for both?

**Comment by blacktop** [comment]
Hi @marco-miller I have added you to the docker hub repo.  I'm not sure if you can now add new Builds or not, but I think you will at least be able to push, so you can at least push up new versions before I get around to adding the auto-build to DH.

**Comment by blacktop** [comment]
make push will work, however, it will just push up say:

blacktop/elasticsearch:7.9

My auto-build changes I just made (plus the `hooks/post_push` I see you updated) will also tag `:latest` as `7.9` as well as `:7`, you could also do that with a series of docker tag/docker push cmds.  I'll add a new make target for doing that soon.  Let me know what you are able to do in DockerHub also.  Thanks again!

**Comment by marco-miller** [comment]
The latest 7.9.1 images I just pushed (not me, the post-push scripting I assume) seem to have worked up there on DH -thanks :) https://hub.docker.com/r/blacktop/elasticsearch/tags

**Pull request merged**
